# Configure the following variables in your repository secrets:
# POETRY_PYPI_TOKEN_PYPI
#
# The POETRY_PYPI_TOKEN_PYPI must be created on: https://pypi.org/manage/account/token/
#
name: Publish package

on:
  release:
    types:
      - created

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.6"

      - name: Install Poetry
        run: pip install --no-input poetry==1.7.1

      - name: Publish package
        run: |
          poetry config pypi-token.pypi "${{ secrets.POETRY_PYPI_TOKEN_PYPI }}"
          poetry publish --build
